// Generated by AI

// dosage : dose  
// frequency : how many dose in day
// strenght : strenght per gallon
// duration how many days

export default function calculateSolute(strength: number, quantity: number) {
    const solute = (strength / 1000000) * quantity;
    return solute.toFixed(3);
}
